/*
  Example Location Key: 208977 (Bandung)
  API: http://dataservice.accuweather.com/forecasts/v1/daily/5day/{locationKey}
*/

export const fiveDays = {
  Headline: {
    EffectiveDate: '2023-04-16T07:00:00+07:00',
    EffectiveEpochDate: 1681603200,
    Severity: 4,
    Text: 'Pleasant Sunday',
    Category: 'mild',
    EndDate: null,
    EndEpochDate: null,
    MobileLink:
      'http://www.accuweather.com/en/id/bandung/208977/daily-weather-forecast/208977?unit=c&lang=en-us',
    Link: 'http://www.accuweather.com/en/id/bandung/208977/daily-weather-forecast/208977?unit=c&lang=en-us',
  },
  DailyForecasts: [
    {
      Date: '2023-04-11T07:00:00+07:00',
      EpochDate: 1681171200,
      Sun: {
        Rise: '2023-04-11T05:51:00+07:00',
        EpochRise: 1681167060,
        Set: '2023-04-11T17:50:00+07:00',
        EpochSet: 1681210200,
      },
      Moon: {
        Rise: '2023-04-11T22:11:00+07:00',
        EpochRise: 1681225860,
        Set: '2023-04-12T11:11:00+07:00',
        EpochSet: 1681272660,
        Phase: 'WaningGibbous',
        Age: 20,
      },
      Temperature: {
        Minimum: {
          Value: 19,
          Unit: 'C',
          UnitType: 17,
        },
        Maximum: {
          Value: 30.9,
          Unit: 'C',
          UnitType: 17,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 19.4,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
        Maximum: {
          Value: 34.4,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Hot',
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 19.4,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
        Maximum: {
          Value: 30.9,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Very Warm',
        },
      },
      HoursOfSun: 3.4,
      DegreeDaySummary: {
        Heating: {
          Value: 0,
          Unit: 'C',
          UnitType: 17,
        },
        Cooling: {
          Value: 7,
          Unit: 'C',
          UnitType: 17,
        },
      },
      AirAndPollen: [
        {
          Name: 'AirQuality',
          Value: 0,
          Category: 'Good',
          CategoryValue: 1,
          Type: 'Ozone',
        },
        {
          Name: 'Grass',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Mold',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Ragweed',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Tree',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'UVIndex',
          Value: 9,
          Category: 'Very High',
          CategoryValue: 4,
        },
      ],
      Day: {
        Icon: 12,
        IconPhrase: 'Showers',
        HasPrecipitation: true,
        PrecipitationType: 'Rain',
        PrecipitationIntensity: 'Light',
        ShortPhrase: 'An a.m. shower, then showers',
        LongPhrase:
          'Mostly cloudy; a shower in spots late this morning followed by showers this afternoon',
        PrecipitationProbability: 83,
        ThunderstormProbability: 24,
        RainProbability: 83,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 14.8,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 308,
            Localized: 'NW',
            English: 'NW',
          },
        },
        WindGust: {
          Speed: {
            Value: 37,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 310,
            Localized: 'NW',
            English: 'NW',
          },
        },
        TotalLiquid: {
          Value: 4.6,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 4.6,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 2,
        HoursOfRain: 2,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 73,
        Evapotranspiration: {
          Value: 3.3,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 3565.8,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Night: {
        Icon: 38,
        IconPhrase: 'Mostly cloudy',
        HasPrecipitation: false,
        ShortPhrase: 'Partly to mostly cloudy',
        LongPhrase: 'Partly to mostly cloudy',
        PrecipitationProbability: 14,
        ThunderstormProbability: 1,
        RainProbability: 14,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 5.6,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 207,
            Localized: 'SSW',
            English: 'SSW',
          },
        },
        WindGust: {
          Speed: {
            Value: 18.5,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 300,
            Localized: 'WNW',
            English: 'WNW',
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 85,
        Evapotranspiration: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 0,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Sources: ['AccuWeather'],
      MobileLink:
        'http://www.accuweather.com/en/id/bandung/208977/daily-weather-forecast/208977?day=1&unit=c&lang=en-us',
      Link: 'http://www.accuweather.com/en/id/bandung/208977/daily-weather-forecast/208977?day=1&unit=c&lang=en-us',
    },
    {
      Date: '2023-04-12T07:00:00+07:00',
      EpochDate: 1681257600,
      Sun: {
        Rise: '2023-04-12T05:51:00+07:00',
        EpochRise: 1681253460,
        Set: '2023-04-12T17:50:00+07:00',
        EpochSet: 1681296600,
      },
      Moon: {
        Rise: '2023-04-12T23:13:00+07:00',
        EpochRise: 1681315980,
        Set: '2023-04-13T12:12:00+07:00',
        EpochSet: 1681362720,
        Phase: 'WaningGibbous',
        Age: 21,
      },
      Temperature: {
        Minimum: {
          Value: 20.1,
          Unit: 'C',
          UnitType: 17,
        },
        Maximum: {
          Value: 28.8,
          Unit: 'C',
          UnitType: 17,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 21.1,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
        Maximum: {
          Value: 35.3,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Hot',
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 21.1,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
        Maximum: {
          Value: 30.7,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Very Warm',
        },
      },
      HoursOfSun: 2.4,
      DegreeDaySummary: {
        Heating: {
          Value: 0,
          Unit: 'C',
          UnitType: 17,
        },
        Cooling: {
          Value: 6,
          Unit: 'C',
          UnitType: 17,
        },
      },
      AirAndPollen: [
        {
          Name: 'AirQuality',
          Value: 0,
          Category: 'Good',
          CategoryValue: 1,
          Type: 'Ozone',
        },
        {
          Name: 'Grass',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Mold',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Ragweed',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Tree',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'UVIndex',
          Value: 7,
          Category: 'High',
          CategoryValue: 3,
        },
      ],
      Day: {
        Icon: 12,
        IconPhrase: 'Showers',
        HasPrecipitation: true,
        PrecipitationType: 'Rain',
        PrecipitationIntensity: 'Moderate',
        ShortPhrase: 'A couple of afternoon showers',
        LongPhrase: 'Mostly cloudy with a couple of showers in the afternoon',
        PrecipitationProbability: 75,
        ThunderstormProbability: 22,
        RainProbability: 75,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 9.3,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 295,
            Localized: 'WNW',
            English: 'WNW',
          },
        },
        WindGust: {
          Speed: {
            Value: 29.6,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 317,
            Localized: 'NW',
            English: 'NW',
          },
        },
        TotalLiquid: {
          Value: 3,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 3,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 2,
        HoursOfRain: 2,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 86,
        Evapotranspiration: {
          Value: 2.5,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 2876.1,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Night: {
        Icon: 35,
        IconPhrase: 'Partly cloudy',
        HasPrecipitation: false,
        ShortPhrase: 'Partly cloudy',
        LongPhrase: 'Partly cloudy',
        PrecipitationProbability: 25,
        ThunderstormProbability: 6,
        RainProbability: 25,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 5.6,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 202,
            Localized: 'SSW',
            English: 'SSW',
          },
        },
        WindGust: {
          Speed: {
            Value: 14.8,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 312,
            Localized: 'NW',
            English: 'NW',
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 85,
        Evapotranspiration: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 0,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Sources: ['AccuWeather'],
      MobileLink:
        'http://www.accuweather.com/en/id/bandung/208977/daily-weather-forecast/208977?day=2&unit=c&lang=en-us',
      Link: 'http://www.accuweather.com/en/id/bandung/208977/daily-weather-forecast/208977?day=2&unit=c&lang=en-us',
    },
    {
      Date: '2023-04-13T07:00:00+07:00',
      EpochDate: 1681344000,
      Sun: {
        Rise: '2023-04-13T05:51:00+07:00',
        EpochRise: 1681339860,
        Set: '2023-04-13T17:49:00+07:00',
        EpochSet: 1681382940,
      },
      Moon: {
        Rise: null,
        EpochRise: null,
        Set: '2023-04-13T12:12:00+07:00',
        EpochSet: 1681362720,
        Phase: 'Last',
        Age: 22,
      },
      Temperature: {
        Minimum: {
          Value: 20.1,
          Unit: 'C',
          UnitType: 17,
        },
        Maximum: {
          Value: 28.1,
          Unit: 'C',
          UnitType: 17,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 21.1,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
        Maximum: {
          Value: 33,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Hot',
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 21.1,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
        Maximum: {
          Value: 31.2,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Very Warm',
        },
      },
      HoursOfSun: 2.3,
      DegreeDaySummary: {
        Heating: {
          Value: 0,
          Unit: 'C',
          UnitType: 17,
        },
        Cooling: {
          Value: 6,
          Unit: 'C',
          UnitType: 17,
        },
      },
      AirAndPollen: [
        {
          Name: 'AirQuality',
          Value: 0,
          Category: 'Good',
          CategoryValue: 1,
          Type: 'Ozone',
        },
        {
          Name: 'Grass',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Mold',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Ragweed',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Tree',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'UVIndex',
          Value: 5,
          Category: 'Moderate',
          CategoryValue: 2,
        },
      ],
      Day: {
        Icon: 18,
        IconPhrase: 'Rain',
        HasPrecipitation: true,
        PrecipitationType: 'Rain',
        PrecipitationIntensity: 'Heavy',
        ShortPhrase: 'Some rain and a thunderstorm',
        LongPhrase:
          'Mostly cloudy and humid with occasional rain and a thunderstorm',
        PrecipitationProbability: 92,
        ThunderstormProbability: 55,
        RainProbability: 92,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 11.1,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 319,
            Localized: 'NW',
            English: 'NW',
          },
        },
        WindGust: {
          Speed: {
            Value: 29.6,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 290,
            Localized: 'WNW',
            English: 'WNW',
          },
        },
        TotalLiquid: {
          Value: 17.4,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 17.4,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 4,
        HoursOfRain: 4,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 89,
        Evapotranspiration: {
          Value: 2.3,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 2816.1,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Night: {
        Icon: 38,
        IconPhrase: 'Mostly cloudy',
        HasPrecipitation: false,
        ShortPhrase: 'Clouds breaking',
        LongPhrase: 'Clouds breaking',
        PrecipitationProbability: 25,
        ThunderstormProbability: 6,
        RainProbability: 25,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 5.6,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 193,
            Localized: 'SSW',
            English: 'SSW',
          },
        },
        WindGust: {
          Speed: {
            Value: 16.7,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 255,
            Localized: 'WSW',
            English: 'WSW',
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 100,
        Evapotranspiration: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 0,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Sources: ['AccuWeather'],
      MobileLink:
        'http://www.accuweather.com/en/id/bandung/208977/daily-weather-forecast/208977?day=3&unit=c&lang=en-us',
      Link: 'http://www.accuweather.com/en/id/bandung/208977/daily-weather-forecast/208977?day=3&unit=c&lang=en-us',
    },
    {
      Date: '2023-04-14T07:00:00+07:00',
      EpochDate: 1681430400,
      Sun: {
        Rise: '2023-04-14T05:51:00+07:00',
        EpochRise: 1681426260,
        Set: '2023-04-14T17:49:00+07:00',
        EpochSet: 1681469340,
      },
      Moon: {
        Rise: '2023-04-14T00:15:00+07:00',
        EpochRise: 1681406100,
        Set: '2023-04-14T13:10:00+07:00',
        EpochSet: 1681452600,
        Phase: 'WaningCrescent',
        Age: 23,
      },
      Temperature: {
        Minimum: {
          Value: 19.5,
          Unit: 'C',
          UnitType: 17,
        },
        Maximum: {
          Value: 29.3,
          Unit: 'C',
          UnitType: 17,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 19.4,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
        Maximum: {
          Value: 34.4,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Hot',
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 19.4,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
        Maximum: {
          Value: 31.1,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Very Warm',
        },
      },
      HoursOfSun: 1.6,
      DegreeDaySummary: {
        Heating: {
          Value: 0,
          Unit: 'C',
          UnitType: 17,
        },
        Cooling: {
          Value: 6,
          Unit: 'C',
          UnitType: 17,
        },
      },
      AirAndPollen: [
        {
          Name: 'AirQuality',
          Value: 0,
          Category: 'Good',
          CategoryValue: 1,
          Type: 'Ozone',
        },
        {
          Name: 'Grass',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Mold',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Ragweed',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Tree',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'UVIndex',
          Value: 6,
          Category: 'High',
          CategoryValue: 3,
        },
      ],
      Day: {
        Icon: 6,
        IconPhrase: 'Mostly cloudy',
        HasPrecipitation: true,
        PrecipitationType: 'Rain',
        PrecipitationIntensity: 'Moderate',
        ShortPhrase: 'A shower in the afternoon',
        LongPhrase: 'Mostly cloudy with a shower in the afternoon',
        PrecipitationProbability: 70,
        ThunderstormProbability: 20,
        RainProbability: 70,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 9.3,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 293,
            Localized: 'WNW',
            English: 'WNW',
          },
        },
        WindGust: {
          Speed: {
            Value: 31.5,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 308,
            Localized: 'NW',
            English: 'NW',
          },
        },
        TotalLiquid: {
          Value: 2.8,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 2.8,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 2,
        HoursOfRain: 2,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 92,
        Evapotranspiration: {
          Value: 2.3,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 2526,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Night: {
        Icon: 7,
        IconPhrase: 'Cloudy',
        HasPrecipitation: false,
        ShortPhrase: 'Cloudy',
        LongPhrase: 'Cloudy',
        PrecipitationProbability: 9,
        ThunderstormProbability: 0,
        RainProbability: 9,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 5.6,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 207,
            Localized: 'SSW',
            English: 'SSW',
          },
        },
        WindGust: {
          Speed: {
            Value: 14.8,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 312,
            Localized: 'NW',
            English: 'NW',
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 93,
        Evapotranspiration: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 0,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Sources: ['AccuWeather'],
      MobileLink:
        'http://www.accuweather.com/en/id/bandung/208977/daily-weather-forecast/208977?day=4&unit=c&lang=en-us',
      Link: 'http://www.accuweather.com/en/id/bandung/208977/daily-weather-forecast/208977?day=4&unit=c&lang=en-us',
    },
    {
      Date: '2023-04-15T07:00:00+07:00',
      EpochDate: 1681516800,
      Sun: {
        Rise: '2023-04-15T05:51:00+07:00',
        EpochRise: 1681512660,
        Set: '2023-04-15T17:48:00+07:00',
        EpochSet: 1681555680,
      },
      Moon: {
        Rise: '2023-04-15T01:16:00+07:00',
        EpochRise: 1681496160,
        Set: '2023-04-15T14:04:00+07:00',
        EpochSet: 1681542240,
        Phase: 'WaningCrescent',
        Age: 24,
      },
      Temperature: {
        Minimum: {
          Value: 19.6,
          Unit: 'C',
          UnitType: 17,
        },
        Maximum: {
          Value: 29.3,
          Unit: 'C',
          UnitType: 17,
        },
      },
      RealFeelTemperature: {
        Minimum: {
          Value: 19.4,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
        Maximum: {
          Value: 35.7,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Hot',
        },
      },
      RealFeelTemperatureShade: {
        Minimum: {
          Value: 19.4,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Pleasant',
        },
        Maximum: {
          Value: 30.9,
          Unit: 'C',
          UnitType: 17,
          Phrase: 'Very Warm',
        },
      },
      HoursOfSun: 3.1,
      DegreeDaySummary: {
        Heating: {
          Value: 0,
          Unit: 'C',
          UnitType: 17,
        },
        Cooling: {
          Value: 6,
          Unit: 'C',
          UnitType: 17,
        },
      },
      AirAndPollen: [
        {
          Name: 'AirQuality',
          Value: 0,
          Category: 'Good',
          CategoryValue: 1,
          Type: 'Ozone',
        },
        {
          Name: 'Grass',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Mold',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Ragweed',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'Tree',
          Value: 0,
          Category: 'Low',
          CategoryValue: 1,
        },
        {
          Name: 'UVIndex',
          Value: 9,
          Category: 'Very High',
          CategoryValue: 4,
        },
      ],
      Day: {
        Icon: 15,
        IconPhrase: 'Thunderstorms',
        HasPrecipitation: true,
        PrecipitationType: 'Rain',
        PrecipitationIntensity: 'Light',
        ShortPhrase: 'Couple of thunderstorms',
        LongPhrase:
          'Mostly cloudy with a couple of showers and a thunderstorm, mainly later',
        PrecipitationProbability: 78,
        ThunderstormProbability: 47,
        RainProbability: 78,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 9.3,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 276,
            Localized: 'W',
            English: 'W',
          },
        },
        WindGust: {
          Speed: {
            Value: 31.5,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 312,
            Localized: 'NW',
            English: 'NW',
          },
        },
        TotalLiquid: {
          Value: 4.5,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 4.5,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 2.5,
        HoursOfRain: 2.5,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 78,
        Evapotranspiration: {
          Value: 2.8,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 3310.2,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Night: {
        Icon: 35,
        IconPhrase: 'Partly cloudy',
        HasPrecipitation: false,
        ShortPhrase: 'Partly cloudy',
        LongPhrase: 'Partly cloudy',
        PrecipitationProbability: 4,
        ThunderstormProbability: 0,
        RainProbability: 4,
        SnowProbability: 0,
        IceProbability: 0,
        Wind: {
          Speed: {
            Value: 5.6,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 200,
            Localized: 'SSW',
            English: 'SSW',
          },
        },
        WindGust: {
          Speed: {
            Value: 16.7,
            Unit: 'km/h',
            UnitType: 7,
          },
          Direction: {
            Degrees: 315,
            Localized: 'NW',
            English: 'NW',
          },
        },
        TotalLiquid: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Rain: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        Snow: {
          Value: 0,
          Unit: 'cm',
          UnitType: 4,
        },
        Ice: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        HoursOfPrecipitation: 0,
        HoursOfRain: 0,
        HoursOfSnow: 0,
        HoursOfIce: 0,
        CloudCover: 70,
        Evapotranspiration: {
          Value: 0,
          Unit: 'mm',
          UnitType: 3,
        },
        SolarIrradiance: {
          Value: 0,
          Unit: 'W/m²',
          UnitType: 33,
        },
      },
      Sources: ['AccuWeather'],
      MobileLink:
        'http://www.accuweather.com/en/id/bandung/208977/daily-weather-forecast/208977?day=5&unit=c&lang=en-us',
      Link: 'http://www.accuweather.com/en/id/bandung/208977/daily-weather-forecast/208977?day=5&unit=c&lang=en-us',
    },
  ],
}
