const url =
  '/locations/v1/cities/geoposition/search?apikey=wxJnfpf0jV48rijOEwWGCLOLvLB6aKfj&q=-6.9217%2C107.6071&details=true&toplevel=true';

const geoposition = {
  Version: 1,
  Key: '208977',
  Type: 'City',
  Rank: 21,
  LocalizedName: 'Bandung',
  EnglishName: 'Bandung',
  PrimaryPostalCode: '',
  Region: {
    ID: 'ASI',
    LocalizedName: 'Asia',
    EnglishName: 'Asia',
  },
  Country: {
    ID: 'ID',
    LocalizedName: 'Indonesia',
    EnglishName: 'Indonesia',
  },
  AdministrativeArea: {
    ID: 'JB',
    LocalizedName: 'West Java',
    EnglishName: 'West Java',
    Level: 1,
    LocalizedType: 'Province',
    EnglishType: 'Province',
    CountryID: 'ID',
  },
  TimeZone: {
    Code: 'WIT',
    Name: 'Asia/Jakarta',
    GmtOffset: 7,
    IsDaylightSaving: false,
    NextOffsetChange: null,
  },
  GeoPosition: {
    Latitude: -6.904,
    Longitude: 107.61,
    Elevation: {
      Metric: {
        Value: 822,
        Unit: 'm',
        UnitType: 5,
      },
      Imperial: {
        Value: 2698,
        Unit: 'ft',
        UnitType: 0,
      },
    },
  },
  IsAlias: false,
  SupplementalAdminAreas: [],
  DataSets: ['AirQualityCurrentConditions', 'AirQualityForecasts', 'Alerts', 'FutureRadar', 'MinuteCast'],
  Details: {
    Key: '208977',
    StationCode: 'WIIB',
    StationGmtOffset: 7,
    BandMap: 'ID',
    Climo: 'JAKX',
    LocalRadar: '',
    MediaRegion: null,
    Metar: 'WIIB',
    NXMetro: '',
    NXState: '',
    Population: 2394873,
    PrimaryWarningCountyCode: '',
    PrimaryWarningZoneCode: '',
    Satellite: 'AUST',
    Synoptic: '96781',
    MarineStation: '',
    MarineStationGMTOffset: null,
    VideoCode: '',
    LocationStem: 'id/bandung/208977',
    PartnerID: null,
    Sources: [
      {
        DataType: 'AirQualityCurrentConditions',
        Source: 'Plume Labs',
        SourceId: 63,
        PartnerSourceUrl: 'https://air.plumelabs.com/air-quality-in-bandung-6VkF',
      },
      {
        DataType: 'AirQualityForecasts',
        Source: 'Plume Labs',
        SourceId: 63,
        PartnerSourceUrl: 'https://air.plumelabs.com/air-quality-in-bandung-6VkF',
      },
      {
        DataType: 'Alerts',
        Source: 'Agency for Meteorology Climatology and Geophysics of Republic Indonesia',
        SourceId: 69,
      },
      {
        DataType: 'Alerts',
        Source: 'United States Geological Survey',
        SourceId: 70,
      },
      {
        DataType: 'CurrentConditions',
        Source: 'AccuWeather',
        SourceId: 1,
      },
      {
        DataType: 'DailyForecast',
        Source: 'AccuWeather',
        SourceId: 1,
      },
      {
        DataType: 'FutureRadar',
        Source: 'AccuWeather',
        SourceId: 1,
      },
      {
        DataType: 'Historical',
        Source: 'AccuWeather',
        SourceId: 1,
      },
      {
        DataType: 'HourlyForecast',
        Source: 'AccuWeather',
        SourceId: 1,
      },
      {
        DataType: 'MinuteCast',
        Source: 'AccuWeather',
        SourceId: 1,
      },
    ],
    CanonicalPostalCode: '',
    CanonicalLocationKey: '208977',
  },
};
